apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
    meta.helm.sh/release-name: actualbudget-actualbudget
    meta.helm.sh/release-namespace: actualbudget
    traefik.ingress.kubernetes.io/router.middlewares: traefik-system-security-headers@kubernetescrd,traefik-system-rate-limit@kubernetescrd
  creationTimestamp: "2026-01-29T13:07:24Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: actualbudget-actualbudget
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/version: 26.1.0
    helm.sh/chart: actualbudget-1.8.6
    helm.toolkit.fluxcd.io/name: actualbudget
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: actualbudget-actualbudget
  namespace: actualbudget
  resourceVersion: "34197039"
  uid: 0a21490c-38ea-4ec0-bc3e-a5f411289941
spec:
  ingressClassName: traefik-system-traefik-system-traefik
  rules:
    - host: actualbudget.kennyandries.com
      http:
        paths:
          - backend:
              service:
                name: actualbudget-actualbudget
                port:
                  number: 5006
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer: {}
