apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  plugin:
    traefik-oidc-auth:
      Secret: urn:k8s:secret:oidc-secret:pluginSecret
      Provider:
        Url: https://auth.kennyandries.com/
        Scopes: ["openid", "profile", "email"]
        ClientId: urn:k8s:secret:oidc-secret:providerClientId
        ClientSecret: urn:k8s:secret:oidc-secret:providerClientSecret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: strict-origin-when-cross-origin
    customResponseHeaders:
      X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  rateLimit:
    average: 100
    burst: 200
    period: 1m
