apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure repositories
  - cert-manager.yaml
  - longhorn.yaml
  - sealed-secrets.yaml
  - stakater.yaml
  - traefik.yaml
  # Application repositories
  - actualbudget.yaml
  - kubito.yaml
  - metrics-server.yaml
  - triliumnext.yaml
  - uptime-kuma.yaml
