apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Kube-vip
  - kube-vip/rbac.yaml
  - kube-vip/daemonset.yaml
  # Cert-manager
  - cert-manager/clusterissuer.yaml
  - cert-manager/sealedsecret.yaml
  # Longhorn
  - longhorn/namespace.yaml
  - longhorn/repo.yaml
  - longhorn/release.yaml
  # Traefik
  - traefik/sealedsecret.yaml
  - traefik/middleware.yaml
  - traefik/certificate.yaml
