apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Kube-vip
  - kube-vip/rbac.yaml
  - kube-vip/daemonset.yaml
  # Cert-manager
  - cert-manager/helmrepo.yaml
  - cert-manager/helmrelease.yaml
  - cert-manager/clusterissuer.yaml
  - cert-manager/sealedsecret.yaml
  # Longhorn
  - longhorn/namespace.yaml
  - longhorn/helmrepo.yaml
  - longhorn/helmrelease.yaml
  # Sealed Secrets
  - sealed-secrets/helmrepo.yaml
  - sealed-secrets/helmrelease.yaml
  # Traefik
  - traefik/helmrepo.yaml
  - traefik/helmrelease.yaml
  # - traefik/sealedsecret.yaml
  - traefik/middleware.yaml
  - traefik/certificate.yaml
