apiVersion: v1
kind: Service
metadata:
  name: servarr-sabnzbd
  namespace: servarr
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
