apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy-servarr.yaml
  - networkpolicy-homepage.yaml
  - networkpolicy-pocket-id.yaml
  - networkpolicy-beszel.yaml
  - networkpolicy-trilium.yaml
  - networkpolicy-actualbudget.yaml
  - networkpolicy-uptime-kuma.yaml
  - networkpolicy-metrics-server.yaml
