apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servarr
  - homepage
  - configarr
  - sabnzbd
  - pocket-id
  - metrics-server
  - actualbudget
  - uptime-kuma
  - beszel
  - trilium
