apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Servarr
  - servarr/namespace.yaml
  - servarr/persistentvolume.yaml
  - servarr/persistentvolumeclaim.yaml
  # Homepage Dashboard
  - homepage/namespace.yaml
  - homepage/rbac.yaml
  - homepage/sealedsecret.yaml
  - homepage/configmap.yaml
  - homepage/service.yaml
  - homepage/deployment.yaml
  - homepage/ingress.yaml
  # Configarr
  - configarr/pvc.yaml
  - configarr/sealedsecret.yaml
  - configarr/configmap.yaml
  - configarr/cronjob.yaml
  # SABnzbd
  - sabnzbd/pvc.yaml
  - sabnzbd/deployment.yaml
  - sabnzbd/service.yaml
  - sabnzbd/ingress.yaml
  # Pocket ID
  - pocket-id/namespace.yaml
  - pocket-id/pvc.yaml
  - pocket-id/deployment.yaml
  - pocket-id/service.yaml
  - pocket-id/ingress.yaml
