apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Servarr
  - servarr/namespace.yaml
  - servarr/persistentvolume.yaml
  - servarr/persistentvolumeclaim.yaml
  - servarr/helmrepo.yaml
  - servarr/helmrelease.yaml
  # Homepage Dashboard
  - homepage/namespace.yaml
  - homepage/rbac.yaml
  - homepage/sealedsecret.yaml
  - homepage/configmap.yaml
  - homepage/service.yaml
  - homepage/deployment.yaml
  - homepage/ingress.yaml
  # Configarr
  - configarr/pvc.yaml
  - configarr/sealedsecret.yaml
  - configarr/configmap.yaml
  - configarr/cronjob.yaml
  # SABnzbd
  - sabnzbd/pvc.yaml
  - sabnzbd/deployment.yaml
  - sabnzbd/service.yaml
  - sabnzbd/ingress.yaml
  # Pocket ID
  - pocket-id/namespace.yaml
  - pocket-id/sealedsecret.yaml
  - pocket-id/pvc.yaml
  - pocket-id/deployment.yaml
  - pocket-id/service.yaml
  - pocket-id/ingress.yaml
  # Metrics Server
  - metrics-server/helmrepo.yaml
  - metrics-server/helmrelease.yaml
  # Actual Budget
  - actualbudget/helmrepo.yaml
  - actualbudget/helmrelease.yaml
  # Uptime Kuma
  - uptime-kuma/helmrepo.yaml
  - uptime-kuma/helmrelease.yaml
  # Beszel
  - beszel/namespace.yaml
  - beszel/sealedsecret.yaml
  - beszel/pvc.yaml
  - beszel/deployment.yaml
  - beszel/service.yaml
  - beszel/ingress.yaml
  - beszel/daemonset.yaml
  # Trilium
  - trilium/helmrepo.yaml
  - trilium/helmrelease.yaml
  - trilium/pvc.yaml
