apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/homepage
  - sealedsecret.yaml
  - configmap.yaml
patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
