apiVersion: v1
kind: Service
metadata:
  name: beszel
  namespace: beszel
  labels:
    app.kubernetes.io/name: beszel
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: beszel
