apiVersion: v1
kind: Service
metadata:
  name: beszel
  namespace: beszel
  labels:
    app.kubernetes.io/name: beszel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: beszel
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
