apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCvGHezDKrUFBmQJl7brUtryyVugPoPCygaYFZj7VZKpkzahiX7Y0KHLskLsoDKq1v7192xNgZV9yq42YK1iXmGqK6Nho6mscMj3tTiTrzywDhor5WIyVnaFktK1DzRJ19Gqe7rrHNXCN8GKYIFrnps0lG/Lrd9m2kW/ySqdnU2ZyhbDtB7nbH5UacViCAKUY0Fhg+t7jU4fV8IfZb6L0P7biMXbbZrj9FmFuzxlY5ofrk1riL3otDIEO+euuucKw/eaS5TqdoDYGnXJI7qO9sg0XzQ4mfGlWEywhmKo1snKvfqq1eL/dsYl+uQwHqmTcPUiHWU/WEBOOQ/etkDIXw/y5HJj0JhW0fMcaFM2xDN70FdIz6rLf8axPlLNg/ppHHflv+eH+DsrEGd9mIeBPMUq60webmOvnY8QkLX3be3tqgj7hCtl9LBxz+fbj7KM/wGMl7ls3v3fSA/96QrfYLrnyzU9NYIfN6mVT0A61pwd+ejBOscnPVecj17+0bJt6OjEN6phQ5+pCHS5Ln+4Gjo+yTm/V1pNBtSHMHoGfQEpp/qZVY9EIVi4H5oRcNq+iZPQjm45qKkcnO1Cj5mYVTVWaUIYSHPVLNhUC9IUN59LfX6Q/IbxPtSnZceFUR680hbPIGTZHHS3uuPTOWJw//sl+0t3+BB6IFySwL2G22v4she0VKFh9dbMUtqnrJhd5pGZvSEpkcqc3fC0q13hFZohQ/K0heQ/KCNZknd3mmVtMcUiD1UzGDeqVozTRmMISlMHMAF9NBusDhT28+Ly/FRJZ9vBDMZo4zq4JLZuZl+RszTxvgaiivC76XX1Tg=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
